// ════════════════════════════════════════════════════════════════════════════
//  mobileDict — dictionnaire FR → Darija (ar) / English (en) pour la traduction
//  automatique de l'app mobile (MobileAutoTranslate).
//
//  Clé = texte FRANÇAIS exact (tel qu'affiché). Valeur = { ar, en }.
//  Tout ce qui n'est PAS dans ce dictionnaire reste en français (repli sûr).
//  À enrichir au fil du temps : ajouter les phrases manquantes ici suffit à les
//  traduire sur TOUS les écrans, sans toucher au code des écrans.
// ════════════════════════════════════════════════════════════════════════════

export interface Tr { ar: string; en: string }

export const MOBILE_DICT: Record<string, Tr> = {
  // ── Actions ───────────────────────────────────────────────────────────────
  "Enregistrer": { ar: "سجّل", en: "Save" },
  "Valider": { ar: "صادق", en: "Validate" },
  "Confirmer": { ar: "أكّد", en: "Confirm" },
  "Annuler": { ar: "لغي", en: "Cancel" },
  "Supprimer": { ar: "حيّد", en: "Delete" },
  "Modifier": { ar: "بدّل", en: "Edit" },
  "Ajouter": { ar: "زيد", en: "Add" },
  "Ajouter une ligne": { ar: "زيد سطر", en: "Add a line" },
  "Fermer": { ar: "سدّ", en: "Close" },
  "Retour": { ar: "رجع", en: "Back" },
  "Suivant": { ar: "اللي من بعد", en: "Next" },
  "Précédent": { ar: "اللي قبل", en: "Previous" },
  "Envoyer": { ar: "صيفط", en: "Send" },
  "Rechercher": { ar: "قلّب", en: "Search" },
  "Rechercher...": { ar: "قلّب...", en: "Search..." },
  "Filtrer": { ar: "صفّي", en: "Filter" },
  "Tout": { ar: "گاع", en: "All" },
  "Tous": { ar: "گاع", en: "All" },
  "Voir tout": { ar: "شوف گاع", en: "See all" },
  "Voir détails": { ar: "شوف التفاصيل", en: "See details" },
  "Détails": { ar: "التفاصيل", en: "Details" },
  "Imprimer": { ar: "طبع", en: "Print" },
  "Télécharger": { ar: "نزّل", en: "Download" },
  "Partager": { ar: "شارك", en: "Share" },
  "Actualiser": { ar: "جدّد", en: "Refresh" },
  "Continuer": { ar: "كمّل", en: "Continue" },
  "Terminer": { ar: "سالي", en: "Finish" },
  "Oui": { ar: "أيه", en: "Yes" },
  "Non": { ar: "لا", en: "No" },
  "OK": { ar: "واخا", en: "OK" },
  "Choisir": { ar: "ختار", en: "Choose" },
  "Sélectionner": { ar: "ختار", en: "Select" },
  "Plus": { ar: "زيد", en: "More" },

  // ── États / statuts ────────────────────────────────────────────────────────
  "En ligne": { ar: "مونلاين", en: "Online" },
  "Hors ligne": { ar: "ماشي مونلاين", en: "Offline" },
  "En attente": { ar: "كيتسنّى", en: "Pending" },
  "En cours": { ar: "ديجا خدّام", en: "In progress" },
  "Validé": { ar: "متصادق", en: "Validated" },
  "Confirmé": { ar: "متأكّد", en: "Confirmed" },
  "Livré": { ar: "توصّل", en: "Delivered" },
  "Annulé": { ar: "متلغي", en: "Cancelled" },
  "Payé": { ar: "مخلّص", en: "Paid" },
  "Non payé": { ar: "ماشي مخلّص", en: "Unpaid" },
  "Brouillon": { ar: "مسوّدة", en: "Draft" },
  "Refusé": { ar: "مرفوض", en: "Refused" },
  "Terminé": { ar: "سالا", en: "Done" },
  "Disponible": { ar: "كاين", en: "Available" },
  "Rupture": { ar: "خاوي", en: "Out of stock" },
  "Actif": { ar: "خدّام", en: "Active" },
  "Inactif": { ar: "ماشي خدّام", en: "Inactive" },
  "Nouveau": { ar: "جديد", en: "New" },
  "Demo": { ar: "تجريبي", en: "Demo" },

  // ── Champs / labels ─────────────────────────────────────────────────────────
  "Nom": { ar: "السمية", en: "Name" },
  "Client": { ar: "الكليان", en: "Client" },
  "Clients": { ar: "الكليانات", en: "Clients" },
  "Fournisseur": { ar: "الفورنيسور", en: "Supplier" },
  "Article": { ar: "السلعة", en: "Item" },
  "Articles": { ar: "السلع", en: "Items" },
  "Produit": { ar: "المنتوج", en: "Product" },
  "Produits": { ar: "المنتوجات", en: "Products" },
  "Famille": { ar: "العائلة", en: "Family" },
  "Quantité": { ar: "الكمية", en: "Quantity" },
  "Qté": { ar: "الكمية", en: "Qty" },
  "Prix": { ar: "الثمن", en: "Price" },
  "Prix d'achat": { ar: "ثمن الشرا", en: "Buy price" },
  "Prix de vente": { ar: "ثمن البيع", en: "Sell price" },
  "Prix unitaire": { ar: "ثمن الوحدة", en: "Unit price" },
  "Total": { ar: "المجموع", en: "Total" },
  "Montant": { ar: "المبلغ", en: "Amount" },
  "Date": { ar: "التاريخ", en: "Date" },
  "Heure": { ar: "الساعة", en: "Time" },
  "Statut": { ar: "الحالة", en: "Status" },
  "Note": { ar: "ملاحظة", en: "Note" },
  "Notes": { ar: "ملاحظات", en: "Notes" },
  "Commentaire": { ar: "تعليق", en: "Comment" },
  "Téléphone": { ar: "التيليفون", en: "Phone" },
  "Adresse": { ar: "العنوان", en: "Address" },
  "Secteur": { ar: "القطاع", en: "Sector" },
  "Zone": { ar: "المنطقة", en: "Zone" },
  "Unité": { ar: "الوحدة", en: "Unit" },
  "Caisse": { ar: "القفّة", en: "Crate" },
  "Caisses": { ar: "القفف", en: "Crates" },
  "Stock": { ar: "الستوك", en: "Stock" },
  "Charge": { ar: "المصروف", en: "Charge" },
  "Charges": { ar: "المصاريف", en: "Charges" },
  "Marge": { ar: "الهامش", en: "Margin" },
  "Remise": { ar: "التخفيض", en: "Discount" },
  "Aujourd'hui": { ar: "اليوم", en: "Today" },
  "Hier": { ar: "البارح", en: "Yesterday" },
  "Cette semaine": { ar: "هاد السيمانة", en: "This week" },
  "Ce mois": { ar: "هاد الشهر", en: "This month" },

  // ── Navigation / écrans ─────────────────────────────────────────────────────
  "Commande": { ar: "الطلبية", en: "Order" },
  "Commandes": { ar: "الطلبيات", en: "Orders" },
  "Nouvelle commande": { ar: "طلبية جديدة", en: "New order" },
  "Achat": { ar: "الشرا", en: "Purchase" },
  "Bon d'achat": { ar: "ورقة الشرا", en: "Purchase note" },
  "Livraison": { ar: "التوصيل", en: "Delivery" },
  "Livraisons": { ar: "التوصيلات", en: "Deliveries" },
  "Préparation": { ar: "التحضير", en: "Preparation" },
  "Réception": { ar: "الاستلام", en: "Receipt" },
  "Retours": { ar: "المرتجعات", en: "Returns" },
  "Bilan": { ar: "الملخص", en: "Report" },
  "Objectifs": { ar: "الأهداف", en: "Targets" },
  "Alertes": { ar: "التنبيهات", en: "Alerts" },
  "Avis": { ar: "الآراء", en: "Reviews" },
  "Mon espace": { ar: "فضائي", en: "My space" },
  "Mes BL": { ar: "وصولاتي", en: "My delivery notes" },
  "Déconnexion": { ar: "خروج", en: "Logout" },
  "Vue": { ar: "العرض", en: "View" },
  "Vue :": { ar: "العرض:", en: "View:" },

  // ── Messages courants ───────────────────────────────────────────────────────
  "Chargement...": { ar: "كيتشارجا...", en: "Loading..." },
  "Envoi...": { ar: "كيتصيفط...", en: "Sending..." },
  "Aucun résultat": { ar: "ماكاين والو", en: "No results" },
  "Aucune donnée": { ar: "ماكاينش الداتا", en: "No data" },
  "Succès": { ar: "نجح", en: "Success" },
  "Erreur": { ar: "خطأ", en: "Error" },
  "Attention": { ar: "ردّ البال", en: "Warning" },
  "Confirmer la suppression ?": { ar: "متأكّد بغيتي تحيّد؟", en: "Confirm deletion?" },
  "Êtes-vous sûr ?": { ar: "متأكّد؟", en: "Are you sure?" },
  "Enregistré": { ar: "تسجّل", en: "Saved" },
  "Enregistré avec succès": { ar: "تسجّل مزيان", en: "Saved successfully" },

  // ── Écran Prévendeur / Commande ─────────────────────────────────────────────
  "Prise de Commande": { ar: "أخذ الطلبية", en: "Order taking" },
  "Passer une commande": { ar: "دير طلبية", en: "Place an order" },
  "Nouveau client": { ar: "كليان جديد", en: "New client" },
  "Nom du client": { ar: "سمية الكليان", en: "Client name" },
  "Créer le client": { ar: "صاوب الكليان", en: "Create client" },
  "Choisir un client": { ar: "ختار كليان", en: "Choose a client" },
  "Sélectionnez un client": { ar: "ختار كليان", en: "Select a client" },
  "Selectionnez un client": { ar: "ختار كليان", en: "Select a client" },
  "Rechercher un client...": { ar: "قلّب على كليان...", en: "Search a client..." },
  "Rechercher par nom...": { ar: "قلّب بالسمية...", en: "Search by name..." },
  "Filtrer les articles...": { ar: "صفّي السلع...", en: "Filter items..." },
  "Aucun article trouve": { ar: "ما لقينا حتى سلعة", en: "No item found" },
  "Aucun client trouvé": { ar: "ما لقينا حتى كليان", en: "No client found" },
  "Catégorie tarifaire": { ar: "فئة الثمن", en: "Price category" },
  "Credit autorise": { ar: "الكريدي مسموح", en: "Credit allowed" },
  "Delai de recouvrement": { ar: "مدة الخلاص", en: "Recovery period" },
  "Heure de livraison": { ar: "وقت التوصيل", en: "Delivery time" },
  "Horaire habituel": { ar: "الوقت المعتاد", en: "Usual time" },
  "Itinéraire": { ar: "الطريق", en: "Route" },
  "Rotation": { ar: "الدوران", en: "Rotation" },
  "Gamme produits": { ar: "گام المنتوجات", en: "Product range" },
  "Entrée de gamme": { ar: "گام بسيط", en: "Entry level" },
  "Moyenne gamme": { ar: "گام متوسط", en: "Mid-range" },
  "Haute gamme": { ar: "گام عالي", en: "High-end" },
  "Standard": { ar: "عادي", en: "Standard" },
  "Marchand": { ar: "تاجر", en: "Merchant" },
  "Particulier": { ar: "خاص", en: "Individual" },
  "Tous les types": { ar: "گاع الأنواع", en: "All types" },
  "Toutes les rotations": { ar: "گاع الدورات", en: "All rotations" },
  "Toutes les tailles": { ar: "گاع الأحجام", en: "All sizes" },
  "Type (préciser)": { ar: "النوع (وضّح)", en: "Type (specify)" },
  "Taille / capacité": { ar: "الحجم / القدرة", en: "Size / capacity" },
  "Stock physique:": { ar: "الستوك الحقيقي:", en: "Physical stock:" },
  "PRIX FIXE": { ar: "ثمن ثابت", en: "FIXED PRICE" },
  "Effacer": { ar: "مسح", en: "Clear" },
  "Réessayer": { ar: "عاود حاول", en: "Retry" },
  "Verrou": { ar: "القفل", en: "Lock" },
  "Verrouillee": { ar: "مقفول", en: "Locked" },
  "Email (optionnel)": { ar: "الإيميل (اختياري)", en: "Email (optional)" },
  "Rue, ville...": { ar: "الزنقة، المدينة...", en: "Street, city..." },
  "Auto-panier": { ar: "السلة الأوتوماتيكية", en: "Auto-cart" },
  "Guide": { ar: "الدليل", en: "Guide" },
  "Enregistrer la visite": { ar: "سجّل الزيارة", en: "Save visit" },
  "Localisation en cours...": { ar: "كنحدّدو الموقع...", en: "Locating..." },
  "Activation GPS en cours...": { ar: "كيتفعّل GPS...", en: "Activating GPS..." },
  "Comment activer le GPS :": { ar: "كيفاش تفعّل GPS:", en: "How to enable GPS:" },
}
